# Generated by Django 4.1.7 on 2023-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.IntegerField(verbose_name='Телеграм чат ID')),
                ('tg_user_id', models.IntegerField(verbose_name='Телеграм пользователь ID')),
                ('verification_code', models.CharField(max_length=10, verbose_name='Код верификации')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Не подтвержден'), (2, 'Подтвержден')], default=1, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
