# Generated by Django 4.1.7 on 2023-05-31 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        ('bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='selected_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь приложения'),
        ),
    ]
